export default {
  id: "nvidia",
  priority: 20,
  hasFree: true,
  alias: "nvidia",
  display: {
    name: "NVIDIA NIM",
    icon: "developer_board",
    color: "#76B900",
    textIcon: "NV",
    website: "https://developer.nvidia.com/nim",
    notice: {
      text: "Free access for NVIDIA Developer Program members (prototyping & testing).",
      apiKeyUrl: "https://build.nvidia.com/settings/api-keys",
    },
  },
  category: "freeTier",
  transport: {
    baseUrl: "https://integrate.api.nvidia.com/v1/chat/completions",
    validateUrl: "https://integrate.api.nvidia.com/v1/models",
  },
  models: [
    { id: "moonshotai/kimi-k2.7", name: "Kimi K2.7" },
    { id: "moonshotai/kimi-k2.7(low)", name: "Kimi K2.7 (Low Thinking)", upstreamModelId: "moonshotai/kimi-k2.7" },
    { id: "moonshotai/kimi-k2.6", name: "Kimi K2.6" },
    { id: "moonshotai/kimi-k2.6(none)", name: "Kimi K2.6 (No/Minimal Thinking)", upstreamModelId: "moonshotai/kimi-k2.6" },
    { id: "moonshotai/kimi-k2.6(low)", name: "Kimi K2.6 (Low Thinking)", upstreamModelId: "moonshotai/kimi-k2.6" },
    { id: "moonshotai/kimi-k2.6(medium)", name: "Kimi K2.6 (Medium Thinking)", upstreamModelId: "moonshotai/kimi-k2.6" },
    { id: "moonshotai/kimi-k2.6(high)", name: "Kimi K2.6 (High Thinking)", upstreamModelId: "moonshotai/kimi-k2.6" },
    { id: "minimaxai/minimax-m2.7", name: "Minimax M2.7" },
    { id: "z-ai/glm4.7", name: "GLM 4.7" },
    { id: "nvidia/nv-embedqa-e5-v5", name: "NV EmbedQA E5 v5", kind: "embedding" },
    { id: "nvidia/parakeet-ctc-1.1b-asr", name: "Parakeet CTC 1.1B", params: ["language"], kind: "stt" },
    { id: "fastpitch", name: "FastPitch", kind: "tts" },
    { id: "tacotron2", name: "Tacotron2", kind: "tts" },
  ],
  serviceKinds: ["llm","tts","embedding"],
  ttsConfig: {
    baseUrl: "https://integrate.api.nvidia.com/v1/audio/speech",
    authType: "apikey",
    authHeader: "bearer",
    format: "nvidia-tts",
  },
  embeddingConfig: { baseUrl: "https://integrate.api.nvidia.com/v1/embeddings", authType: "apikey", authHeader: "bearer" },
};
